#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Ensure Nginx listens on port 80
sudo sed -i 's/# listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# listen 

\[::\]

:80 default_server;/listen 

\[::\]

:80 default_server;/g' /etc/nginx/sites-available/default

# Modify the default HTML file to include "Holberton School"
echo 'Holberton School for the win!' | sudo tee /var/www/html/index.html

# Restart Nginx using service
sudo service nginx restart
